import { Router } from 'express';
import { requireAuth, requireRole } from '../../middleware/auth.js';
import { writeLimiter } from '../../middleware/rateLimit.js';
import { profilRouter } from './profil.js';
import { dashboardRouter } from './dashboard.js';
import { krsRouter } from './krs.js';
import { jadwalRouter } from './jadwal.js';
import { nilaiRouter } from './nilai.js';
import { absensiRouter } from './absensi.js';
import { pengumumanRouter } from './pengumuman.js';
import { mbkmRouter } from './mbkm.js';
import { edomRouter } from './edom.js';
import { skripsiRouter } from './skripsi.js';
import { yudisiumRouter } from './yudisium.js';
import { bahanAjarRouter } from './bahan-ajar.js';
import { beasiswaRouter } from './beasiswa.js';
import { tugasRouter } from './tugas.js';
import { suratRouter } from './surat.js';
import { keuanganRouter } from './keuangan.js';
import { triDharmaRouter } from './tri-dharma.js';
import { konsultasiRouter } from './konsultasi.js';
import { kuisRouter } from './kuis.js';
import { tiketRouter } from './tiket.js';
import { skpiRouter } from './skpi.js';
import { mutasiRouter } from './mutasi.js';
import { sertifikatRouter } from './sertifikat.js';
import { prestasiRouter } from './prestasi.js';
import { sertifikasiRouter } from './sertifikasi.js';
import { heregistrasiRouter } from './heregistrasi.js';

export const mahasiswaRouter = Router();

mahasiswaRouter.use(requireAuth, requireRole('mahasiswa'));
mahasiswaRouter.use((req, res, next) => {
  if (['POST', 'PATCH', 'DELETE', 'PUT'].includes(req.method)) return writeLimiter(req, res, next);
  next();
});
mahasiswaRouter.use(profilRouter);
mahasiswaRouter.use(dashboardRouter);
mahasiswaRouter.use(krsRouter);
mahasiswaRouter.use(jadwalRouter);
mahasiswaRouter.use(nilaiRouter);
mahasiswaRouter.use(absensiRouter);
mahasiswaRouter.use(pengumumanRouter);
mahasiswaRouter.use(mbkmRouter);
mahasiswaRouter.use(edomRouter);
mahasiswaRouter.use(skripsiRouter);
mahasiswaRouter.use(yudisiumRouter);
mahasiswaRouter.use(bahanAjarRouter);
mahasiswaRouter.use(beasiswaRouter);
mahasiswaRouter.use(tugasRouter);
mahasiswaRouter.use(suratRouter);
mahasiswaRouter.use(keuanganRouter);
mahasiswaRouter.use(triDharmaRouter);
mahasiswaRouter.use(konsultasiRouter);
mahasiswaRouter.use(kuisRouter);
mahasiswaRouter.use(tiketRouter);
mahasiswaRouter.use(skpiRouter);
mahasiswaRouter.use(mutasiRouter);
mahasiswaRouter.use(sertifikatRouter);
mahasiswaRouter.use(prestasiRouter);
mahasiswaRouter.use(sertifikasiRouter);
mahasiswaRouter.use(heregistrasiRouter);
