import { describe, it, expect, beforeAll, beforeEach, afterAll } from 'vitest';
import request from 'supertest';
import { createApp } from '../../src/app.js';
import { prisma } from '../../src/db.js';
import { createFixtures, resetDb, disconnectDb, loginAs, type Fixtures } from './helpers.js';

const app = createApp();
let f: Fixtures;

beforeAll(async () => { await resetDb(); });
afterAll(async () => { await resetDb(); await disconnectDb(); });
beforeEach(async () => {
  await resetDb();
  f = await createFixtures();
});

describe('Akademik kelola users', () => {
  it('list users + filter role + search', async () => {
    const token = await loginAs(request(app), f.akademikUser.email);
    const r1 = await request(app).get('/akademik/users').set('Authorization', `Bearer ${token}`);
    expect(r1.status).toBe(200);
    expect(r1.body.total).toBeGreaterThanOrEqual(3); // akademik + dosen + mahasiswa

    const r2 = await request(app).get('/akademik/users?role=mahasiswa').set('Authorization', `Bearer ${token}`);
    expect(r2.body.items.every((u: any) => u.role === 'mahasiswa')).toBe(true);

    const r3 = await request(app).get(`/akademik/users?q=${f.mahasiswa.nim}`).set('Authorization', `Bearer ${token}`);
    expect(r3.body.items.some((u: any) => u.mahasiswa?.nim === f.mahasiswa.nim)).toBe(true);
  });

  it('reset password auto-generate → password baru bisa dipakai login', async () => {
    const akdToken = await loginAs(request(app), f.akademikUser.email);
    const r = await request(app).post(`/akademik/users/${f.mahasiswaUser.id}/reset-password`).set('Authorization', `Bearer ${akdToken}`).send({});
    expect(r.status).toBe(200);
    expect(r.body.autoGenerated).toBe(true);
    expect(r.body.passwordMustChange).toBe(true);
    expect(typeof r.body.password).toBe('string');

    // Login pakai password baru
    const newPw = r.body.password as string;
    const login = await request(app).post('/auth/login').send({ identifier: f.mahasiswa.nim, password: newPw });
    expect(login.status).toBe(200);
    expect(login.body.user.passwordMustChange).toBe(true);
  });

  it('reset password custom + revoke semua sesi', async () => {
    // Login dulu untuk buat sesi
    await loginAs(request(app), f.mahasiswa.nim);
    const sebelum = await prisma.refreshToken.count({ where: { userId: f.mahasiswaUser.id, revokedAt: null } });
    expect(sebelum).toBe(1);

    const akdToken = await loginAs(request(app), f.akademikUser.email);
    const r = await request(app).post(`/akademik/users/${f.mahasiswaUser.id}/reset-password`).set('Authorization', `Bearer ${akdToken}`)
      .send({ password: 'PasswordBaru12345' });
    expect(r.body.autoGenerated).toBe(false);
    expect(r.body.password).toBe('PasswordBaru12345');

    const sesudah = await prisma.refreshToken.count({ where: { userId: f.mahasiswaUser.id, revokedAt: null } });
    expect(sesudah).toBe(0);
  });

  it('deactivate user → tidak bisa login lagi + semua sesi revoked', async () => {
    await loginAs(request(app), f.mahasiswa.nim);
    const akdToken = await loginAs(request(app), f.akademikUser.email);
    const r = await request(app).post(`/akademik/users/${f.mahasiswaUser.id}/deactivate`).set('Authorization', `Bearer ${akdToken}`);
    expect(r.status).toBe(200);

    const u = await prisma.user.findUnique({ where: { id: f.mahasiswaUser.id } });
    expect(u!.isActive).toBe(false);
    expect(await prisma.refreshToken.count({ where: { userId: f.mahasiswaUser.id, revokedAt: null } })).toBe(0);

    const login = await request(app).post('/auth/login').send({ identifier: f.mahasiswa.nim, password: 'password123' });
    expect(login.status).toBe(401);
  });

  it('tidak boleh deactivate akun sendiri', async () => {
    const akdToken = await loginAs(request(app), f.akademikUser.email);
    const r = await request(app).post(`/akademik/users/${f.akademikUser.id}/deactivate`).set('Authorization', `Bearer ${akdToken}`);
    expect(r.status).toBe(400);
  });

  it('activate kembali → bisa login', async () => {
    const akdToken = await loginAs(request(app), f.akademikUser.email);
    await request(app).post(`/akademik/users/${f.mahasiswaUser.id}/deactivate`).set('Authorization', `Bearer ${akdToken}`);
    await request(app).post(`/akademik/users/${f.mahasiswaUser.id}/activate`).set('Authorization', `Bearer ${akdToken}`);
    const login = await request(app).post('/auth/login').send({ identifier: f.mahasiswa.nim, password: 'password123' });
    expect(login.status).toBe(200);
  });

  it('list sessions + revoke 1 sesi', async () => {
    await loginAs(request(app), f.mahasiswa.nim);
    const akdToken = await loginAs(request(app), f.akademikUser.email);
    const r = await request(app).get(`/akademik/users/${f.mahasiswaUser.id}/sessions`).set('Authorization', `Bearer ${akdToken}`);
    expect(r.body.items.length).toBe(1);
    const id = r.body.items[0].id;
    const del = await request(app).delete(`/akademik/users/${f.mahasiswaUser.id}/sessions/${id}`).set('Authorization', `Bearer ${akdToken}`);
    expect(del.status).toBe(204);
    const r2 = await request(app).get(`/akademik/users/${f.mahasiswaUser.id}/sessions`).set('Authorization', `Bearer ${akdToken}`);
    expect(r2.body.items.length).toBe(0);
  });

  it('force-password-change toggle', async () => {
    const akdToken = await loginAs(request(app), f.akademikUser.email);
    const r = await request(app).post(`/akademik/users/${f.mahasiswaUser.id}/force-password-change`).set('Authorization', `Bearer ${akdToken}`).send({ value: true });
    expect(r.body.passwordMustChange).toBe(true);
    const u = await prisma.user.findUnique({ where: { id: f.mahasiswaUser.id } });
    expect(u!.passwordMustChange).toBe(true);
  });

  it('change-password berhasil → clear passwordMustChange', async () => {
    // Set force change
    await prisma.user.update({ where: { id: f.mahasiswaUser.id }, data: { passwordMustChange: true } });
    const mhsToken = await loginAs(request(app), f.mahasiswa.nim);
    const r = await request(app).post('/auth/change-password').set('Authorization', `Bearer ${mhsToken}`)
      .send({ currentPassword: 'password123', newPassword: 'BaruBangetLahYa' });
    expect(r.status).toBe(200);
    const u = await prisma.user.findUnique({ where: { id: f.mahasiswaUser.id } });
    expect(u!.passwordMustChange).toBe(false);
  });

  it('lastLoginAt ter-update saat login', async () => {
    const before = await prisma.user.findUnique({ where: { id: f.mahasiswaUser.id }, select: { lastLoginAt: true } });
    expect(before!.lastLoginAt).toBeNull();
    await loginAs(request(app), f.mahasiswa.nim);
    const after = await prisma.user.findUnique({ where: { id: f.mahasiswaUser.id }, select: { lastLoginAt: true } });
    expect(after!.lastLoginAt).not.toBeNull();
  });
});

describe('RBAC user management', () => {
  it('mahasiswa tidak boleh akses endpoint akademik', async () => {
    const token = await loginAs(request(app), f.mahasiswa.nim);
    const r = await request(app).get('/akademik/users').set('Authorization', `Bearer ${token}`);
    expect(r.status).toBe(403);
  });

  it('dosen tidak boleh reset password user lain', async () => {
    const token = await loginAs(request(app), f.dosenUser.email);
    const r = await request(app).post(`/akademik/users/${f.mahasiswaUser.id}/reset-password`).set('Authorization', `Bearer ${token}`).send({});
    expect(r.status).toBe(403);
  });
});
