import { describe, it, expect, beforeAll, beforeEach, afterAll } from 'vitest';
import request from 'supertest';
import { createApp } from '../../src/app.js';
import { prisma } from '../../src/db.js';
import { createFixtures, resetDb, disconnectDb, loginAs, type Fixtures } from './helpers.js';

const app = createApp();
let f: Fixtures;

beforeAll(async () => { await resetDb(); });
afterAll(async () => { await resetDb(); await disconnectDb(); });
beforeEach(async () => {
  await resetDb();
  f = await createFixtures();
});

describe('Akademik kelola wali', () => {
  it('buat wali baru → password auto-generate + link mahasiswa', async () => {
    const akdToken = await loginAs(request(app), f.akademikUser.email);
    const r = await request(app).post('/akademik/wali').set('Authorization', `Bearer ${akdToken}`)
      .send({
        email: 'orangtua.aisyah@gmail.com',
        nama: 'Bapak Putra',
        telepon: '08123456789',
        mahasiswaIds: [f.mahasiswa.id],
        hubungan: 'ayah',
      });
    expect(r.status).toBe(201);
    expect(r.body.autoGenerated).toBe(true);
    expect(r.body.password).toBeTruthy();

    // Verify user record
    const u = await prisma.user.findUnique({ where: { email: 'orangtua.aisyah@gmail.com' } });
    expect(u!.role).toBe('wali');
    expect(u!.passwordMustChange).toBe(true);
  });

  it('email duplikat → 409', async () => {
    const akdToken = await loginAs(request(app), f.akademikUser.email);
    await request(app).post('/akademik/wali').set('Authorization', `Bearer ${akdToken}`)
      .send({ email: 'wali1@test.id', nama: 'Wali Tes', mahasiswaIds: [f.mahasiswa.id] });
    const r = await request(app).post('/akademik/wali').set('Authorization', `Bearer ${akdToken}`)
      .send({ email: 'wali1@test.id', nama: 'Wali Lain', mahasiswaIds: [f.mahasiswa.id] });
    expect(r.status).toBe(409);
  });

  it('mahasiswa tidak ada → 400', async () => {
    const akdToken = await loginAs(request(app), f.akademikUser.email);
    const r = await request(app).post('/akademik/wali').set('Authorization', `Bearer ${akdToken}`)
      .send({ email: 'wali2@test.id', nama: 'Wali Tes', mahasiswaIds: ['00000000-0000-0000-0000-000000000000'] });
    expect(r.status).toBe(400);
  });

  it('list + search wali', async () => {
    const akdToken = await loginAs(request(app), f.akademikUser.email);
    await request(app).post('/akademik/wali').set('Authorization', `Bearer ${akdToken}`)
      .send({ email: 'rudi@test.id', nama: 'Rudi Hartono', mahasiswaIds: [f.mahasiswa.id] });
    const r = await request(app).get('/akademik/wali?q=Rudi').set('Authorization', `Bearer ${akdToken}`);
    expect(r.body.items.length).toBe(1);
  });

  it('link tambahan mahasiswa → idempotensi 409', async () => {
    const akdToken = await loginAs(request(app), f.akademikUser.email);
    const c = await request(app).post('/akademik/wali').set('Authorization', `Bearer ${akdToken}`)
      .send({ email: 'wali-link@test.id', nama: 'Wali Tes', mahasiswaIds: [f.mahasiswa.id] });
    const r = await request(app).post(`/akademik/wali/${c.body.id}/link`).set('Authorization', `Bearer ${akdToken}`)
      .send({ mahasiswaId: f.mahasiswa.id });
    expect(r.status).toBe(409);
  });
});

describe('Wali portal — read-only dashboard', () => {
  async function buatWali() {
    const akdToken = await loginAs(request(app), f.akademikUser.email);
    const r = await request(app).post('/akademik/wali').set('Authorization', `Bearer ${akdToken}`)
      .send({ email: 'walitest@test.id', nama: 'Ortu Aisyah', mahasiswaIds: [f.mahasiswa.id] });
    return { email: 'walitest@test.id', password: r.body.password as string, waliId: r.body.id as string };
  }

  it('wali login → akses profil + anak', async () => {
    const { email, password } = await buatWali();
    // login
    const loginR = await request(app).post('/auth/login').send({ identifier: email, password });
    expect(loginR.status).toBe(200);
    expect(loginR.body.user.role).toBe('wali');

    const token = loginR.body.accessToken;
    const profil = await request(app).get('/wali/profil').set('Authorization', `Bearer ${token}`);
    expect(profil.body.nama).toBe('Ortu Aisyah');
    expect(profil.body.anak).toHaveLength(1);
    expect(profil.body.anak[0].nim).toBe(f.mahasiswa.nim);
  });

  it('dashboard anak: IPK, KRS, absensi, tagihan', async () => {
    const { email, password } = await buatWali();
    const loginR = await request(app).post('/auth/login').send({ identifier: email, password });
    const token = loginR.body.accessToken;

    // Tambah nilai finalized untuk IPK
    const krs = await prisma.krs.create({
      data: { mahasiswaId: f.mahasiswa.id, kelasId: f.kelas1.id, semesterId: f.semester.id, status: 'disetujui' },
    });
    await prisma.nilai.create({
      data: { krsId: krs.id, mahasiswaId: f.mahasiswa.id, nilaiAngka: 85, nilaiHuruf: 'A', bobot: 4.0, status: 'finalized' },
    });

    const r = await request(app).get(`/wali/mahasiswa/${f.mahasiswa.id}/dashboard`).set('Authorization', `Bearer ${token}`);
    expect(r.status).toBe(200);
    expect(r.body.mahasiswa.nim).toBe(f.mahasiswa.nim);
    expect(r.body.ipk).toBeCloseTo(4.0, 1);
    expect(r.body.krsCount).toBe(1);
  });

  it('wali tidak bisa akses dashboard mahasiswa lain', async () => {
    const { email, password } = await buatWali();
    const loginR = await request(app).post('/auth/login').send({ identifier: email, password });
    const token = loginR.body.accessToken;

    // Buat mahasiswa kedua, wali tidak ter-link
    const pw = (await import('../../src/lib/password.js')).hashPassword;
    const h = await pw('password123');
    const mhs2 = await prisma.user.create({
      data: {
        email: 'mhs2@test.id', passwordHash: h, role: 'mahasiswa',
        mahasiswa: { create: { nim: '9999000002', nama: 'Mhs2', jenisKelamin: 'L', angkatan: 2024, prodiId: f.prodi.id } },
      },
      include: { mahasiswa: true },
    });
    const r = await request(app).get(`/wali/mahasiswa/${mhs2.mahasiswa!.id}/dashboard`).set('Authorization', `Bearer ${token}`);
    expect(r.status).toBe(403);
  });

  it('transkrip anak return nilai finalized', async () => {
    const { email, password } = await buatWali();
    const loginR = await request(app).post('/auth/login').send({ identifier: email, password });
    const token = loginR.body.accessToken;

    const krs = await prisma.krs.create({
      data: { mahasiswaId: f.mahasiswa.id, kelasId: f.kelas1.id, semesterId: f.semester.id, status: 'disetujui' },
    });
    await prisma.nilai.create({
      data: { krsId: krs.id, mahasiswaId: f.mahasiswa.id, nilaiAngka: 75, nilaiHuruf: 'B', bobot: 3.0, status: 'finalized' },
    });

    const r = await request(app).get(`/wali/mahasiswa/${f.mahasiswa.id}/transkrip`).set('Authorization', `Bearer ${token}`);
    expect(r.body.items.length).toBe(1);
    expect(r.body.items[0].nilaiHuruf).toBe('B');
  });
});

describe('RBAC wali', () => {
  it('mahasiswa tidak boleh akses endpoint wali', async () => {
    const token = await loginAs(request(app), f.mahasiswa.nim);
    const r = await request(app).get('/wali/profil').set('Authorization', `Bearer ${token}`);
    expect(r.status).toBe(403);
  });

  it('mahasiswa tidak boleh akses endpoint akademik wali', async () => {
    const token = await loginAs(request(app), f.mahasiswa.nim);
    const r = await request(app).get('/akademik/wali').set('Authorization', `Bearer ${token}`);
    expect(r.status).toBe(403);
  });

  it('wali tidak boleh akses endpoint mahasiswa', async () => {
    const akdToken = await loginAs(request(app), f.akademikUser.email);
    const c = await request(app).post('/akademik/wali').set('Authorization', `Bearer ${akdToken}`)
      .send({ email: 'walicobaakses@test.id', nama: 'Wali Tes', mahasiswaIds: [f.mahasiswa.id] });
    const loginR = await request(app).post('/auth/login').send({ identifier: 'walicobaakses@test.id', password: c.body.password });
    const r = await request(app).get('/mahasiswa/profil').set('Authorization', `Bearer ${loginR.body.accessToken}`);
    expect(r.status).toBe(403);
  });
});
