import { Router } from 'express';
import { requireAuth, requireRole } from '../../middleware/auth.js';
import { writeLimiter } from '../../middleware/rateLimit.js';
import { profilRouter } from './profil.js';
import { dashboardRouter } from './dashboard.js';
import { jadwalRouter } from './jadwal.js';
import { kelasRouter } from './kelas.js';
import { absensiRouter } from './absensi.js';
import { pengumumanRouter } from './pengumuman.js';
import { skripsiRouter } from './skripsi.js';
import { bahanAjarRouter } from './bahan-ajar.js';
import { tugasRouter } from './tugas.js';
import { bimbinganRouter } from './bimbingan.js';
import { penelitianRouter } from './penelitian.js';
import { pengabdianRouter } from './pengabdian.js';
import { konsultasiRouter } from './konsultasi.js';
import { kuisRouter } from './kuis.js';
import { dpaDashboardRouter } from './dpa-dashboard.js';
import { bkdRouter } from './bkd.js';
import { cpmkRouter } from './cpmk.js';
import { ewsRouter as dosenEwsRouter } from './ews.js';

export const dosenRouter = Router();

dosenRouter.use(requireAuth, requireRole('dosen'));
dosenRouter.use((req, res, next) => {
  if (['POST', 'PATCH', 'DELETE', 'PUT'].includes(req.method)) return writeLimiter(req, res, next);
  next();
});
dosenRouter.use(profilRouter);
dosenRouter.use(dashboardRouter);
dosenRouter.use(jadwalRouter);
dosenRouter.use(kelasRouter);
dosenRouter.use(absensiRouter);
dosenRouter.use(pengumumanRouter);
dosenRouter.use(skripsiRouter);
dosenRouter.use(bahanAjarRouter);
dosenRouter.use(tugasRouter);
dosenRouter.use(bimbinganRouter);
dosenRouter.use(penelitianRouter);
dosenRouter.use(pengabdianRouter);
dosenRouter.use(konsultasiRouter);
dosenRouter.use(kuisRouter);
dosenRouter.use(dpaDashboardRouter);
dosenRouter.use(bkdRouter);
dosenRouter.use(cpmkRouter);
dosenRouter.use(dosenEwsRouter);
