import { Router } from 'express';
import { requireAuth, requireRole } from '../../middleware/auth.js';
import { writeLimiter } from '../../middleware/rateLimit.js';
import { profilRouter } from './profil.js';
import { dashboardRouter } from './dashboard.js';
import { laporanRouter } from './laporan.js';
import { mahasiswaRouter } from './mahasiswa.js';
import { dosenRouter } from './dosen.js';
import { kurikulumRouter } from './kurikulum.js';
import { periodeRouter } from './periode.js';
import { krsRouter } from './krs.js';
import { keuanganRouter } from './keuangan.js';
import { kknRouter } from './kkn.js';
import { mbkmRouter } from './mbkm.js';
import { edomRouter } from './edom.js';
import { skripsiRouter } from './skripsi.js';
import { yudisiumRouter } from './yudisium.js';
import { beasiswaRouter } from './beasiswa.js';
import { suratRouter } from './surat.js';
import { pengumumanRouter } from './pengumuman.js';
import { kalenderRouter } from './kalender.js';
import { tiketRouter } from './tiket.js';
import { skpiRouter } from './skpi.js';
import { mutasiRouter } from './mutasi.js';
import { akreditasiRouter } from './akreditasi.js';
import { usersRouter } from './users.js';
import { dokumenAdminRouter } from './dokumen.js';
import { feederRouter } from './feeder.js';
import { bkdAdminRouter } from './bkd.js';
import { waliAdminRouter } from './wali.js';
import { obeRouter } from './obe.js';
import { sertifikatAdminRouter } from './sertifikat.js';
import { spmiStandarRouter } from './spmi-standar.js';
import { spmiAmiRouter } from './spmi-ami.js';
import { spmiRtmRouter } from './spmi-rtm.js';
import { spmiSurveiRouter } from './spmi-survei.js';
import { spmiDashboardRouter } from './spmi-dashboard.js';
import { spmiLaporanRouter } from './spmi-laporan.js';
import { institusiAdminRouter } from './institusi.js';
import { prestasiAdminRouter } from './prestasi.js';
import { sertifikasiAdminRouter } from './sertifikasi.js';
import { oversightRouter } from './oversight.js';
import { kategoriUktRouter } from './kategori-ukt.js';
import { heregistrasiAdminRouter } from './heregistrasi.js';
import { ewsRouter } from './ews.js';
import { auditRouter } from './audit.js';
import { skalaNilaiRouter } from './skala-nilai.js';

export const akademikRouter = Router();

akademikRouter.use(requireAuth, requireRole('akademik'));
// rate-limit mutation untuk semua subroute akademik
akademikRouter.use((req, res, next) => {
  if (['POST', 'PATCH', 'DELETE', 'PUT'].includes(req.method)) return writeLimiter(req, res, next);
  next();
});
akademikRouter.use(profilRouter);
akademikRouter.use(dashboardRouter);
akademikRouter.use(laporanRouter);
akademikRouter.use(mahasiswaRouter);
akademikRouter.use(dosenRouter);
akademikRouter.use(kurikulumRouter);
akademikRouter.use(periodeRouter);
akademikRouter.use(krsRouter);
akademikRouter.use(keuanganRouter);
akademikRouter.use(kknRouter);
akademikRouter.use(mbkmRouter);
akademikRouter.use(edomRouter);
akademikRouter.use(skripsiRouter);
akademikRouter.use(yudisiumRouter);
akademikRouter.use(beasiswaRouter);
akademikRouter.use(suratRouter);
akademikRouter.use(pengumumanRouter);
akademikRouter.use(kalenderRouter);
akademikRouter.use(tiketRouter);
akademikRouter.use(skpiRouter);
akademikRouter.use(mutasiRouter);
akademikRouter.use(akreditasiRouter);
akademikRouter.use(usersRouter);
akademikRouter.use(dokumenAdminRouter);
akademikRouter.use(feederRouter);
akademikRouter.use(bkdAdminRouter);
akademikRouter.use(waliAdminRouter);
akademikRouter.use(obeRouter);
akademikRouter.use(sertifikatAdminRouter);
akademikRouter.use(spmiStandarRouter);
akademikRouter.use(spmiAmiRouter);
akademikRouter.use(spmiRtmRouter);
akademikRouter.use(spmiSurveiRouter);
akademikRouter.use(spmiDashboardRouter);
akademikRouter.use(spmiLaporanRouter);
akademikRouter.use(institusiAdminRouter);
akademikRouter.use(prestasiAdminRouter);
akademikRouter.use(sertifikasiAdminRouter);
akademikRouter.use(oversightRouter);
akademikRouter.use(kategoriUktRouter);
akademikRouter.use(heregistrasiAdminRouter);
akademikRouter.use(ewsRouter);
akademikRouter.use(auditRouter);
akademikRouter.use(skalaNilaiRouter);
