import { Router } from 'express';
import { z } from 'zod';
import crypto from 'node:crypto';
import { prisma } from '../../db.js';
import { BadRequest, Conflict, NotFound } from '../../lib/errors.js';
import { writeAudit } from '../../lib/audit.js';
import { hashPassword } from '../../lib/password.js';

export const waliAdminRouter = Router();

const HUBUNGAN = ['ayah', 'ibu', 'kakak', 'saudara', 'wali_lain'] as const;

const createSchema = z.object({
  email: z.string().email().max(120),
  password: z.string().min(8).max(120).optional().nullable(),
  nama: z.string().min(2).max(120),
  telepon: z.string().max(40).optional().nullable(),
  alamat: z.string().max(500).optional().nullable(),
  pekerjaan: z.string().max(100).optional().nullable(),
  mahasiswaIds: z.array(z.string().uuid()).min(1),
  hubungan: z.enum(HUBUNGAN).default('wali_lain'),
});

/** List wali. */
waliAdminRouter.get('/wali', async (req, res) => {
  const q = req.query.q as string | undefined;
  const items = await prisma.wali.findMany({
    where: q ? {
      OR: [
        { nama: { contains: q } },
        { user: { email: { contains: q } } },
        { mahasiswa: { some: { mahasiswa: { OR: [{ nim: { contains: q } }, { nama: { contains: q } }] } } } },
      ],
    } : undefined,
    include: {
      user: { select: { email: true, isActive: true, lastLoginAt: true } },
      mahasiswa: {
        include: { mahasiswa: { select: { id: true, nim: true, nama: true, prodi: { select: { kode: true } } } } },
      },
    },
    orderBy: { createdAt: 'desc' },
    take: 200,
  });
  res.json({ items });
});

/** Detail wali. */
waliAdminRouter.get('/wali/:id', async (req, res) => {
  const w = await prisma.wali.findUnique({
    where: { id: req.params.id },
    include: {
      user: { select: { email: true, isActive: true, lastLoginAt: true } },
      mahasiswa: {
        include: { mahasiswa: { select: { id: true, nim: true, nama: true, angkatan: true, prodi: { select: { kode: true, nama: true } } } } },
      },
    },
  });
  if (!w) throw NotFound('Wali tidak ditemukan');
  res.json(w);
});

/** Buat akun wali baru sekaligus link ke mahasiswa. */
waliAdminRouter.post('/wali', async (req, res) => {
  const body = createSchema.parse(req.body);

  // Pastikan email belum dipakai
  const existing = await prisma.user.findUnique({ where: { email: body.email } });
  if (existing) throw Conflict('Email sudah dipakai user lain');

  // Validasi semua mahasiswaIds ada
  const mhsCount = await prisma.mahasiswa.count({ where: { id: { in: body.mahasiswaIds } } });
  if (mhsCount !== body.mahasiswaIds.length) throw BadRequest('Salah satu mahasiswa tidak ditemukan');

  const tempPw = body.password ?? crypto.randomBytes(9).toString('base64url');
  const hash = await hashPassword(tempPw);

  const wali = await prisma.user.create({
    data: {
      email: body.email,
      passwordHash: hash,
      role: 'wali',
      passwordMustChange: true,
      wali: {
        create: {
          nama: body.nama,
          telepon: body.telepon ?? null,
          alamat: body.alamat ?? null,
          pekerjaan: body.pekerjaan ?? null,
          mahasiswa: {
            create: body.mahasiswaIds.map((mid) => ({ mahasiswaId: mid, hubungan: body.hubungan })),
          },
        },
      },
    },
    include: { wali: true },
  });

  void writeAudit(req, { action: 'wali.create', entity: 'wali', entityId: wali.wali!.id, metadata: { mahasiswaIds: body.mahasiswaIds } });

  res.status(201).json({
    id: wali.wali!.id,
    userId: wali.id,
    email: wali.email,
    nama: body.nama,
    password: tempPw,
    autoGenerated: !body.password,
  });
});

const linkSchema = z.object({
  mahasiswaId: z.string().uuid(),
  hubungan: z.enum(HUBUNGAN).default('wali_lain'),
});

/** Link tambahan mahasiswa ke wali yang sudah ada. */
waliAdminRouter.post('/wali/:id/link', async (req, res) => {
  const w = await prisma.wali.findUnique({ where: { id: req.params.id } });
  if (!w) throw NotFound('Wali tidak ditemukan');
  const body = linkSchema.parse(req.body);
  const mhs = await prisma.mahasiswa.findUnique({ where: { id: body.mahasiswaId } });
  if (!mhs) throw BadRequest('Mahasiswa tidak ditemukan');
  try {
    const link = await prisma.waliMahasiswa.create({
      data: { waliId: w.id, mahasiswaId: body.mahasiswaId, hubungan: body.hubungan },
    });
    res.status(201).json(link);
  } catch (e: any) {
    if (e?.code === 'P2002') throw Conflict('Mahasiswa sudah ter-link ke wali ini');
    throw e;
  }
});

/** Unlink mahasiswa dari wali. */
waliAdminRouter.delete('/wali/:id/link/:mahasiswaId', async (req, res) => {
  const link = await prisma.waliMahasiswa.findUnique({
    where: { waliId_mahasiswaId: { waliId: req.params.id, mahasiswaId: req.params.mahasiswaId } },
  });
  if (!link) throw NotFound('Link tidak ditemukan');
  await prisma.waliMahasiswa.delete({ where: { id: link.id } });
  res.status(204).end();
});
