import { useMutation, useQueryClient } from '@tanstack/react-query';
import { api, apiPost } from './api';
import { useApi } from './queries';

export type Role = 'mahasiswa' | 'dosen' | 'akademik';
export type AkademikSubRole = 'super_admin' | 'akademik' | 'keuangan' | 'prodi' | 'spmi';

export type AdminUser = {
  id: string;
  email: string;
  role: Role;
  isActive: boolean;
  passwordMustChange: boolean;
  lastLoginAt: string | null;
  createdAt: string;
  mahasiswa?: { id: string; nim: string; nama: string; prodi: { kode: string; nama: string } } | null;
  dosen?: { id: string; nidn: string; nama: string; prodi: { kode: string; nama: string } } | null;
  akademik?: {
    id: string;
    nama: string;
    jabatan: string | null;
    subRole?: AkademikSubRole;
    prodi?: { id: string; kode: string; nama: string } | null;
  } | null;
  _count?: { refreshTokens: number };
};

export const useAdminUsers = (filters: { role?: Role; status?: 'aktif' | 'nonaktif'; q?: string } = {}) => {
  const qs = new URLSearchParams();
  if (filters.role) qs.set('role', filters.role);
  if (filters.status) qs.set('status', filters.status);
  if (filters.q) qs.set('q', filters.q);
  return useApi<{ items: AdminUser[]; total: number; take: number; skip: number }>(['admin-users', qs.toString()], `/akademik/users?${qs}`);
};

export type UserSession = { id: string; userAgent: string | null; ip: string | null; createdAt: string; expiresAt: string };
export const useAdminUserSessions = (userId: string | undefined) =>
  useApi<{ items: UserSession[] }>(['admin-user-sessions', userId ?? ''], `/akademik/users/${userId}/sessions`, { enabled: !!userId });

export function useAdminUserActions(userId?: string) {
  const qc = useQueryClient();
  const inv = () => {
    qc.invalidateQueries({ queryKey: ['admin-users'] });
    if (userId) qc.invalidateQueries({ queryKey: ['admin-user-sessions', userId] });
  };
  return {
    resetPassword: useMutation({
      mutationFn: ({ id, password, forceChange }: { id: string; password?: string | null; forceChange?: boolean }) =>
        apiPost(`/akademik/users/${id}/reset-password`, { password, forcePasswordChange: forceChange }) as Promise<{ ok: boolean; password: string; autoGenerated: boolean; passwordMustChange: boolean }>,
      onSuccess: inv,
    }),
    deactivate: useMutation({
      mutationFn: (id: string) => apiPost(`/akademik/users/${id}/deactivate`, {}),
      onSuccess: inv,
    }),
    activate: useMutation({
      mutationFn: (id: string) => apiPost(`/akademik/users/${id}/activate`, {}),
      onSuccess: inv,
    }),
    forcePasswordChange: useMutation({
      mutationFn: ({ id, value }: { id: string; value: boolean }) => apiPost(`/akademik/users/${id}/force-password-change`, { value }),
      onSuccess: inv,
    }),
    revokeSession: useMutation({
      mutationFn: ({ id, tokenId }: { id: string; tokenId: string }) => api(`/akademik/users/${id}/sessions/${tokenId}`, { method: 'DELETE' }),
      onSuccess: inv,
    }),
    revokeAllSessions: useMutation({
      mutationFn: (id: string) => api(`/akademik/users/${id}/sessions`, { method: 'DELETE' }),
      onSuccess: inv,
    }),
    updateSubRole: useMutation({
      mutationFn: ({ id, subRole, prodiId }: { id: string; subRole: AkademikSubRole; prodiId?: string | null }) =>
        api(`/akademik/users/${id}/akademik-sub-role`, {
          method: 'PATCH',
          body: JSON.stringify({ subRole, prodiId: prodiId ?? null }),
        }),
      onSuccess: inv,
    }),
  };
}
