import { useMutation, useQueryClient } from '@tanstack/react-query';
import { api, apiPost } from './api';
import { useApi } from './queries';

export type HubunganWali = 'ayah' | 'ibu' | 'kakak' | 'saudara' | 'wali_lain';

// ---------- Wali portal ----------

export type WaliProfil = {
  id: string;
  nama: string;
  email: string;
  telepon: string | null;
  alamat: string | null;
  pekerjaan: string | null;
  anak: Array<{
    id: string;
    nim: string;
    nama: string;
    angkatan: number;
    status: string;
    prodi: { kode: string; nama: string; fakultas: { nama: string } };
    hubungan: HubunganWali;
  }>;
};

export type WaliDashboard = {
  mahasiswa: {
    id: string; nim: string; nama: string; angkatan: number; status: string;
    prodi: { kode: string; nama: string };
    dpa: { nidn: string; nama: string; gelarDepan: string | null; gelarBelakang: string | null } | null;
  };
  semester: { kode: string; nama: string } | null;
  ipk: number;
  sksLulus: number;
  sksAmbil: number;
  krsCount: number;
  krsItems: Array<{ kodeMK: string; namaMK: string; sks: number; status: string }>;
  absensi: { hadir: number; izin: number; sakit: number; alpa: number; total: number; persenHadir: number | null };
  tagihan: { total: number; belumLunas: number; count: number };
};

export type WaliTranskrip = {
  items: Array<{
    semester: string;
    kodeMK: string;
    namaMK: string;
    sks: number;
    nilaiHuruf: string | null;
    bobot: number | null;
  }>;
};

export const useWaliProfil = () =>
  useApi<WaliProfil>(['wali-profil'], '/wali/profil');

export const useWaliDashboard = (mahasiswaId: string | undefined) =>
  useApi<WaliDashboard>(['wali-dashboard', mahasiswaId ?? ''], `/wali/mahasiswa/${mahasiswaId}/dashboard`, { enabled: !!mahasiswaId });

export const useWaliTranskrip = (mahasiswaId: string | undefined) =>
  useApi<WaliTranskrip>(['wali-transkrip', mahasiswaId ?? ''], `/wali/mahasiswa/${mahasiswaId}/transkrip`, { enabled: !!mahasiswaId });

// ---------- Akademik manage ----------

export type WaliAdmin = {
  id: string;
  nama: string;
  telepon: string | null;
  alamat: string | null;
  pekerjaan: string | null;
  user: { email: string; isActive: boolean; lastLoginAt: string | null };
  mahasiswa: Array<{
    hubungan: HubunganWali;
    mahasiswa: { id: string; nim: string; nama: string; angkatan?: number; prodi: { kode: string; nama?: string } };
  }>;
};

export const useAdminWali = (q?: string) => {
  const qs = q ? `?q=${encodeURIComponent(q)}` : '';
  return useApi<{ items: WaliAdmin[] }>(['admin-wali', q ?? ''], `/akademik/wali${qs}`);
};

export type WaliInput = {
  email: string;
  password?: string | null;
  nama: string;
  telepon?: string | null;
  alamat?: string | null;
  pekerjaan?: string | null;
  mahasiswaIds: string[];
  hubungan?: HubunganWali;
};

export function useAdminWaliActions() {
  const qc = useQueryClient();
  const inv = () => qc.invalidateQueries({ queryKey: ['admin-wali'] });
  return {
    create: useMutation({
      mutationFn: (body: WaliInput) =>
        apiPost<{ id: string; userId: string; email: string; nama: string; password: string; autoGenerated: boolean }>(
          '/akademik/wali', body,
        ),
      onSuccess: inv,
    }),
    link: useMutation({
      mutationFn: ({ id, mahasiswaId, hubungan }: { id: string; mahasiswaId: string; hubungan: HubunganWali }) =>
        apiPost(`/akademik/wali/${id}/link`, { mahasiswaId, hubungan }),
      onSuccess: inv,
    }),
    unlink: useMutation({
      mutationFn: ({ id, mahasiswaId }: { id: string; mahasiswaId: string }) =>
        api(`/akademik/wali/${id}/link/${mahasiswaId}`, { method: 'DELETE' }),
      onSuccess: inv,
    }),
  };
}
